spring.jmx:
  enabled: false

server:
  port: 8092

security:
  basic:
    enabled: false

management:
  port: 8093
  security:
    enabled: false

project:
  name: web-service-1
  version: 0.1
  description: description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

order.service:
  name: 'default profile:'
---
spring:
  profiles: mysql

order.service:
  name: 'test profile:'